### ISSUE TITLE
cli command kedro databricks bundle

### ISSUE THREAD

**Issue by theoclipse** [JenspederM/kedro-databricks#54]
Hello,

We found that command `kedro databricks bundle` does not add parameter `--package-name {package_name}`.

I found that parameter is added only if kedro version is less than 0.19.8 (in file utils.py function `require_databricks_run_script`)

Is there a reason for that ? For us, this parameter is still needed, otherwise job is not righly executed on databricks

**Comment by jpm-halfspace** [comment]
Prior to version 0.19.8, a custom run script was required to run the pipeline on data bricks. After this, we can now utilize the kedro client, which doesn't accept a `--package-name` argument.
