### ISSUE TITLE
Add var argument in kedro databricks bundle cli

### ISSUE THREAD

**Issue by theoclipse** [JenspederM/kedro-databricks#76]
var parameter already exists in databricks bundle cli, and enable to define a set of environment variable ( ex: --var="my_env_key:my_env_value") that can be interpreted in config yaml files.

**Comment by JenspederM** [comment]
@theoclipse I'm not sure if we can do this with click, but preferably I'd want to follow the Databricks way of doing this where you can have multiple `--var` in one statement
