### ISSUE TITLE
tarfile filter was implemented in Python 3.12

### ISSUE THREAD

**Issue by jpm-halfspace** [JenspederM/kedro-databricks#83]

**Comment by JenspederM** [comment]
tarfile.extractall is used in `DeployController.upload_project_config` to unpack and upload environment specific configuration to Databricks. However, it uses the `filter` argument which was added in python 3.12 rendering the framework unusable for earlier versions of Python.

<img width="834" alt="image" src="https://github.com/user-attachments/assets/a3ddfac0-2445-4c9e-9f28-1aef18fa9a1b">
